Mark vc-bzr-test-fauilt-bzr-autoloads as unstable for now
Currently the test fails like this:

  Running 3 tests (2018-12-17 12:17:43-0600)
     passed  1/3  vc-bzr-test-bug9726
  Mark set
  Press C-c C-c when you are done editing.
  Enter a change comment.  Type C-c C-c when done
     passed  2/3  vc-bzr-test-bug9781
  Falling back on "slow" status detection ((file-missing "Opening input file" "No such file or directory" "/tmp/vc-bzr-testVlgmsb/bzr/.bzr/checkout/dirstate"))
  Error: (error "Running bzr status --no-classify loaddefs.el...FAILED (status 3)")
  Warnings in `bzr' output: bzr: ERROR: invalid header line: ''

  Error: (error "Running bzr status --no-classify loaddefs.el...FAILED (status 3)")
  Warnings in `bzr' output: bzr: ERROR: invalid header line: ''

  Test vc-bzr-test-faulty-bzr-autoloads backtrace:
    logand(nil 128)
    vc-mode-line("/tmp/vc-bzr-testVlgmsb/bzr/loaddefs.el" Bzr)
    vc-refresh-state()
    run-hooks(find-file-hook)
    after-find-file(t t)
    find-file-noselect-1(#<buffer loaddefs.el> "/tmp/vc-bzr-testVlgmsb/b
    find-file-noselect("/tmp/vc-bzr-testVlgmsb/bzr/loaddefs.el")
    autoload-find-generated-file()
    update-directory-autoloads("/tmp/vc-bzr-testVlgmsb/bzr/")
    (progn (update-directory-autoloads default-directory) t)
    (setq value-35 (progn (update-directory-autoloads default-directory)
    (unwind-protect (setq value-35 (progn (update-directory-autoloads de
    (if (unwind-protect (setq value-35 (progn (update-directory-autoload
    (let (form-description-36) (if (unwind-protect (setq value-35 (progn
    (let ((value-35 (gensym "ert-form-evaluation-aborted-"))) (let (form
    (progn (call-process vc-bzr-program nil nil nil "init") (let ((temp-
    (unwind-protect (progn (call-process vc-bzr-program nil nil nil "ini
    (let* ((homedir (make-temp-file "vc-bzr-test" t)) (bzrdir (expand-fi
    (lambda nil (let* ((fn-30 (function executable-find)) (args-31 (cond
    ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
    ert-run-test(#s(ert-test :name vc-bzr-test-faulty-bzr-autoloads :doc
    ert-run-or-rerun-test(#s(ert--stats :selector (not (or (tag :expensi
    ert-run-tests((not (or (tag :expensive-test) (tag :unstable))) #f(co
    ert-run-tests-batch((not (or (tag :expensive-test) (tag :unstable)))
    ert-run-tests-batch-and-exit((not (or (tag :expensive-test) (tag :un
    eval((ert-run-tests-batch-and-exit '(not (or (tag :expensive-test) (
    command-line-1(("-L" ":/home/locke/tmp/main-26.1/debian/build-src/te
    command-line()
    normal-top-level()
  Test vc-bzr-test-faulty-bzr-autoloads condition:
      (wrong-type-argument number-or-marker-p nil)
     FAILED  3/3  vc-bzr-test-faulty-bzr-autoloads

  Ran 3 tests, 2 results as expected, 1 unexpected (2018-12-17 12:17:46-0600)

  1 unexpected results:
     FAILED  vc-bzr-test-faulty-bzr-autoloads