emacs-common: add "Breaks: prom-mew (<= 2.00+3.2am01-1)"
Apparently it was removed from the archive in 2009 and can no longer
install:

  Install prom-mew for emacs24
  install/prom-mew: Handling install for emacsen flavor emacs24
  ERROR: install script from prom-mew package failed
  dpkg: error processing package emacs24 (--configure):
   subprocess installed post-installation script returned error exit status 1

Thanks to Andreas Beckmann for reporting the problem.

Closes: 851604