Don't clear FONTCONFIG_LIBS and FONTCONFIG_CFLAGS in configure.
The build should no longer fail when linking with --no-add-needed

Previously, configure would clear FONTCONFIG_LIBS and
FONTCONFIG_CFLAGS.  This would break the build when compiling with a
linker that defaults to --no-add-needed.  For example:

  /usr/bin/ld: ftfont.o: undefined reference to symbol 'FcInit'

configure should no longer clear these variables.

Author: Reinhard Tartler <siretart@tauware.de>
Added-by: Rob Browning <rlb@defaultvalue.org>