emacs-common: add "Breaks: mell (<= 1.0.0-7)"
Apparently it was removed from the archive in 2011 and can no longer
install:

  Install mell for emacs24
  install/mell: Handling install for emacsen flavor emacs24...
  ERROR: install script from mell package failed
  dpkg: error processing package emacs24 (--configure):
   subprocess installed post-installation script returned error exit status 1

Thanks to Andreas Beckmann for reporting the problem.

Closes: 860858